# Generated by Django 4.2.15 on 2024-08-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
